services:
  nginx:
    image: nginx:1.25.5
    container_name: nginx
    depends_on:
      - fastapi_app
    ports:
      - "80:80"
    configs:
      - source: nginx-config
        target: /etc/nginx/conf.d/default.conf
        mode: 0444

  fastapi_app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fastapi_app
    expose:
      - 8000
    configs:
      - source: backend_env
        target: /etc/secrets/.env  # путь файла в контейнере
        mode: 0444
    restart: always

volumes:
  postgres_data:

configs:
  nginx-config:
    file: ./nginx/nginx.conf
  backend_env:
    file: /etc/secrets/.env

