"""image_url no longer exists

Revision ID: 10c682ac3701
Revises: a2539b46e267
Create Date: 2024-01-14 14:56:50.557681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "10c682ac3701"
down_revision: Union[str, None] = "a2539b46e267"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "artwork", "year_created", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_constraint("image_image_url_key", "image", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("image_image_url_key", "image", ["image_url"])
    op.alter_column(
        "artwork", "year_created", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
