"""Update artist

Revision ID: 1546ee27c97f
Revises: dac38be6cfd9
Create Date: 2024-01-03 18:20:08.052425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1546ee27c97f"
down_revision: Union[str, None] = "dac38be6cfd9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "artist", "links", existing_type=sa.VARCHAR(length=1000), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "artist", "links", existing_type=sa.VARCHAR(length=1000), nullable=True
    )
    # ### end Alembic commands ###
