"""Fix artist and artwork relationship

Revision ID: 1659dcbc2151
Revises: d69db2a32a57
Create Date: 2024-04-27 18:39:21.752913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1659dcbc2151'
down_revision: Union[str, None] = 'd69db2a32a57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
