"""remove ArtworkModeration

Revision ID: 3bc9f8d37103
Revises: fdaf8927ba0e
Create Date: 2024-06-10 18:48:00.820727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3bc9f8d37103'
down_revision: Union[str, None] = 'fdaf8927ba0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_artwork_moderation_id', table_name='artwork_moderation')
    op.drop_table('artwork_moderation')
    op.create_foreign_key(None, 'artwork', 'artwork_location', ['location_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artwork', type_='foreignkey')
    op.create_table('artwork_moderation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('artwork_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='artworkmoderationstatus'), autoincrement=False, nullable=False),
    sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artwork_id'], ['artwork.id'], name='artwork_moderation_artwork_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='artwork_moderation_pkey'),
    sa.UniqueConstraint('artwork_id', name='artwork_moderation_artwork_id_key')
    )
    op.create_index('ix_artwork_moderation_id', 'artwork_moderation', ['id'], unique=False)
    # ### end Alembic commands ###
