"""Multiple artist

Revision ID: 6145e6ce0132
Revises: 668dc5beb798
Create Date: 2024-03-09 20:34:22.560548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6145e6ce0132'
down_revision: Union[str, None] = '668dc5beb798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authorship', sa.Column('artwork_id', sa.Integer(), nullable=False))
    op.drop_index('ix_authorship_user_id', table_name='authorship')
    op.create_index(op.f('ix_authorship_artwork_id'), 'authorship', ['artwork_id'], unique=False)
    op.drop_constraint('authorship_user_id_fkey', 'authorship', type_='foreignkey')
    op.create_foreign_key(None, 'authorship', 'artwork', ['artwork_id'], ['id'])
    op.drop_column('authorship', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authorship', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'authorship', type_='foreignkey')
    op.create_foreign_key('authorship_user_id_fkey', 'authorship', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_authorship_artwork_id'), table_name='authorship')
    op.create_index('ix_authorship_user_id', 'authorship', ['user_id'], unique=False)
    op.drop_column('authorship', 'artwork_id')
    # ### end Alembic commands ###
