"""Artist and festival image

Revision ID: 65f3001549d5
Revises: ccedaf16ed5b
Create Date: 2024-01-14 15:11:00.591017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65f3001549d5'
down_revision: Union[str, None] = 'ccedaf16ed5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'artist', 'image', ['image_id'], ['id'])
    op.add_column('festival', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'festival', 'image', ['image_id'], ['id'])
    op.drop_constraint('image_image_url_key', 'image', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('image_image_url_key', 'image', ['image_url'])
    op.drop_constraint(None, 'festival', type_='foreignkey')
    op.drop_column('festival', 'image_id')
    op.drop_constraint(None, 'artist', type_='foreignkey')
    op.drop_column('artist', 'image_id')
    # ### end Alembic commands ###
