"""Multiple artist

Revision ID: 668dc5beb798
Revises: e4b6ec55b995
Create Date: 2024-03-09 20:29:57.685463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '668dc5beb798'
down_revision: Union[str, None] = 'e4b6ec55b995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authorship_artist_id'), 'authorship', ['artist_id'], unique=False)
    op.create_index(op.f('ix_authorship_user_id'), 'authorship', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_authorship_user_id'), table_name='authorship')
    op.drop_index(op.f('ix_authorship_artist_id'), table_name='authorship')
    op.drop_table('authorship')
    # ### end Alembic commands ###
