"""add blurhash into image

Revision ID: 924700bcfda6
Revises: cb65aeb98c07
Create Date: 2024-05-22 11:33:12.004918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '924700bcfda6'
down_revision: Union[str, None] = 'cb65aeb98c07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'artwork', 'artwork_location', ['location_id'], ['id'], use_alter=True)
    op.add_column('image', sa.Column('blurhash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'blurhash')
    op.drop_constraint(None, 'artwork', type_='foreignkey')
    # ### end Alembic commands ###
