"""Modified the existing  models

Revision ID: 9603dfa7c9fd
Revises: baac8f1b4d87
Create Date: 2023-11-03 16:32:33.646732

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9603dfa7c9fd"
down_revision: Union[str, None] = "baac8f1b4d87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "artwork_images",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("artwork_images", "created_at")
    # ### end Alembic commands ###
