"""Some changes in inheritance models

Revision ID: 99f8ad99a1cb
Revises: 37256df44112
Create Date: 2024-01-05 09:03:39.677682

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "99f8ad99a1cb"
down_revision: Union[str, None] = "37256df44112"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artwork_ticket",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("artwork_id", sa.Integer(), nullable=True),
        sa.Column("artwork_data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["artwork_id"],
            ["artwork.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["ticket.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_artwork_ticket_artwork_id"),
        "artwork_ticket",
        ["artwork_id"],
        unique=False,
    )
    op.drop_index("ix_ticket_artwork_id", table_name="ticket")
    op.drop_constraint("tickets_artwork_id_fkey", "ticket", type_="foreignkey")
    op.drop_column("ticket", "artwork_data")
    op.drop_column("ticket", "artwork_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ticket",
        sa.Column("artwork_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "ticket",
        sa.Column(
            "artwork_data",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_foreign_key(
        "tickets_artwork_id_fkey", "ticket", "artwork", ["artwork_id"], ["id"]
    )
    op.create_index("ix_ticket_artwork_id", "ticket", ["artwork_id"], unique=False)
    op.drop_index(op.f("ix_artwork_ticket_artwork_id"), table_name="artwork_ticket")
    op.drop_table("artwork_ticket")
    # ### end Alembic commands ###
