"""change user model

Revision ID: 9f75ab209293
Revises: c7559fd87e85
Create Date: 2023-12-03 21:57:22.172508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f75ab209293'
down_revision: Union[str, None] = 'c7559fd87e85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reaction',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('artworks_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artworks_id'], ['artworks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'artworks_id')
    )
    op.drop_index('ix_moderator_user_id', table_name='moderator')
    op.drop_table('moderator')
    op.drop_constraint('artworks_artist_id_fkey', 'artworks', type_='foreignkey')
    op.create_foreign_key(None, 'artworks', 'artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artworks', type_='foreignkey')
    op.create_foreign_key('artworks_artist_id_fkey', 'artworks', 'user', ['artist_id'], ['id'])
    op.create_table('moderator',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='moderator_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='moderator_pkey')
    )
    op.create_index('ix_moderator_user_id', 'moderator', ['user_id'], unique=False)
    op.drop_table('reaction')
    # ### end Alembic commands ###
