"""Lazy settings"

Revision ID: a11c5bad7def
Revises: ce05aa6b696b
Create Date: 2024-01-09 15:44:26.003817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a11c5bad7def"
down_revision: Union[str, None] = "ce05aa6b696b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "festival",
        "name",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=70),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "festival",
        "name",
        existing_type=sa.String(length=70),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
