"""Create reactions

Revision ID: b0fe3f91a5e8
Revises: 9f75ab209293
Create Date: 2023-12-07 19:02:24.826778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0fe3f91a5e8'
down_revision: Union[str, None] = '9f75ab209293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reaction')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reaction',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('artworks_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artworks_id'], ['artworks.id'], name='reaction_artworks_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='reaction_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'artworks_id', name='reaction_pkey')
    )
    # ### end Alembic commands ###
