"""Create Festival

Revision ID: ce05aa6b696b
Revises: 8dc94edf8de1
Create Date: 2024-01-05 21:20:49.551399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce05aa6b696b'
down_revision: Union[str, None] = '8dc94edf8de1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('festival',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=320), nullable=True),
    sa.Column('links', sa.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_festival_name'), 'festival', ['name'], unique=False)
    op.add_column('artworks', sa.Column('festival_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'artworks', 'festival', ['festival_id'], ['id'])
    op.drop_column('artworks', 'festival')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artworks', sa.Column('festival', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'artworks', type_='foreignkey')
    op.drop_column('artworks', 'festival_id')
    op.drop_index(op.f('ix_festival_name'), table_name='festival')
    op.drop_table('festival')
    # ### end Alembic commands ###
