"""Multiple artist

Revision ID: d69db2a32a57
Revises: 6145e6ce0132
Create Date: 2024-03-09 20:37:08.276023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd69db2a32a57'
down_revision: Union[str, None] = '6145e6ce0132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artwork_artist_id_fkey', 'artwork', type_='foreignkey')
    op.drop_column('artwork', 'artist_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artwork', sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('artwork_artist_id_fkey', 'artwork', 'artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###
