"""Change artist

Revision ID: dac38be6cfd9
Revises: c7559fd87e85
Create Date: 2023-12-26 20:42:09.576226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dac38be6cfd9'
down_revision: Union[str, None] = 'c7559fd87e85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_moderator_user_id', table_name='moderator')
    op.drop_table('moderator')
    op.add_column('artist', sa.Column('name', sa.String(length=50), nullable=False))
    op.add_column('artist', sa.Column('description', sa.String(length=320), nullable=True))
    op.add_column('artist', sa.Column('links', sa.String(length=1000), nullable=True))
    op.alter_column('artist', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_artist_name'), 'artist', ['name'], unique=False)
    op.drop_constraint('artworks_artist_id_fkey', 'artworks', type_='foreignkey')
    op.create_foreign_key(None, 'artworks', 'artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artworks', type_='foreignkey')
    op.create_foreign_key('artworks_artist_id_fkey', 'artworks', 'user', ['artist_id'], ['id'])
    op.drop_index(op.f('ix_artist_name'), table_name='artist')
    op.alter_column('artist', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('artist', 'links')
    op.drop_column('artist', 'description')
    op.drop_column('artist', 'name')
    op.create_table('moderator',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='moderator_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='moderator_pkey')
    )
    op.create_index('ix_moderator_user_id', 'moderator', ['user_id'], unique=False)
    # ### end Alembic commands ###
