"""Multiple artist

Revision ID: e4b6ec55b995
Revises: 80d376ae858b
Create Date: 2024-03-09 20:28:15.207478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4b6ec55b995'
down_revision: Union[str, None] = '80d376ae858b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_authorship_artist_id', table_name='authorship')
    op.drop_index('ix_authorship_user_id', table_name='authorship')
    op.drop_table('authorship')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorship',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], name='authorship_artist_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='authorship_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='authorship_pkey')
    )
    op.create_index('ix_authorship_user_id', 'authorship', ['user_id'], unique=False)
    op.create_index('ix_authorship_artist_id', 'authorship', ['artist_id'], unique=False)
    # ### end Alembic commands ###
